### ISSUE TITLE
Theograph in the Barrett's section isnt plotting correctly

### ISSUE THREAD

**Issue by sebastiz** [nhs-r-community/shinyEndomineR#35]
The Theograph asks for the hospital number and date field. When these are selected the plot doesnt update. Also there appear to be two date fields in the drop down but I am unclear why

**Comment by ChrisBeeley** [comment]
As far as I can tell, there isn't enough data in the example data to draw this graph correctly. The hospital number and date controls were extraneous and have been removed. I think it should work correctly with more data, but cannot test it without making more data available

**Comment by ChrisBeeley** [comment]
Closed by #47
