### ISSUE TITLE
Unable to debug inside of golem module

### ISSUE THREAD

**Issue by sebastiz** [nhs-r-community/shinyEndomineR#40]
This is probably ignorance on my part but I dont seem to be able to debug inside of the golem module in the same way I would for a shiny app. Adding browser() adds a browse the first time I run the app (ie before the data is loaded) but doesnt run again once the data is loaded. I've also tried to add a browser button to the app but no joy. Is there a way to debug this app that is golem specific?

**Comment by ChrisBeeley** [comment]
'''R

observe({

  cat(str(example_data))

})
  

'''

Untested but this should print the contents of example_data to the console
